name: Node CI
on: [pull_request]

jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Danger
        run: yarn danger ci
        env: 
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      - name: Debug Enviroment Variables
        run: |
          echo "DANGER_GITHUB_API_TOKEN: $DANGER_GITHUB_API_TOKEN"